convert house1.png -transparent white house1.png
convert house2.png -transparent white house2.png
convert chest1.png -transparent white chest1.png
convert smith.png -transparent white smith.png
convert dojo.png -transparent white dojo.png
convert gazebo.png -transparent white gazebo.png
convert hotspring.png -transparent white hotspring.png
convert library.png -transparent white library.png
convert inn.png -transparent white inn.png